steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/iq6900-backend', '.']

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iq6900-backend']

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iq6900-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iq6900-backend'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      # 환경변수는 Cloud Build 트리거에서 설정
      - '--set-env-vars'
      - '${_ENV_VARS}'  # Cloud Build 트리거에서 정의

images:
  - 'gcr.io/$PROJECT_ID/iq6900-backend'

options:
  logging: CLOUD_LOGGING_ONLY