steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/iq-testbackend', '.']  # 여기 수정

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iq-testbackend']  # 여기 수정

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'iq-testbackend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iq-testbackend'  # 여기 수정
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - '${_ENV_VARS}'

images:
  - 'gcr.io/$PROJECT_ID/iq-testbackend'

options:
  logging: CLOUD_LOGGING_ONLY